import { Product } from "./types";

export const CATEGORIES = ["All", "Sarees", "Lehengas", "Kurtis", "Anarkalis", "Suits"];

const u = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=600&q=80`;

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Royal Bridal Lehenga",
    price: 499.99,
    category: "Lehengas",
    rating: 4.9,
    reviews: 124,
    image: u("photo-1610189012906-478338104311"),
    description: "A stunning red velvet lehenga with intricate gold zari work and mirror detailing. Perfect for weddings and grand receptions.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Red", "Maroon"],
    new: true,
    stock: 10
  },
  {
    id: "2",
    name: "Pastel Floral Kurti Set",
    price: 89.99,
    category: "Kurtis",
    rating: 4.7,
    reviews: 89,
    image: u("photo-1583391726247-bd7475808a66"),
    description: "Comfortable cotton kurta with delicate floral prints, paired with white churidar and a matching dupatta. Ideal for daily wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Peach", "Mint"],
    new: true,
    stock: 25
  },
  {
    id: "3",
    name: "Banarasi Silk Saree",
    price: 299.50,
    category: "Sarees",
    rating: 4.8,
    reviews: 210,
    image: u("photo-1558618666-fcd25c85cd64"),
    description: "Authentic Banarasi silk saree in royal blue with silver zari border. Comes with a matching blouse piece.",
    sizes: ["Free Size"],
    colors: ["Blue", "Green", "Purple"],
    new: false,
    stock: 15
  },
  {
    id: "4",
    name: "Golden Anarkali Suit",
    price: 179.99,
    category: "Anarkalis",
    rating: 4.9,
    reviews: 156,
    image: u("photo-1529374255404-311a2a4f1fd9"),
    description: "Heavy embroidered golden Anarkali suit with velvet texture. A statement piece for festive occasions.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gold", "Beige"],
    new: true,
    stock: 8
  },
  {
    id: "5",
    name: "Embroidered Chiffon Saree",
    price: 149.99,
    category: "Sarees",
    rating: 4.6,
    reviews: 340,
    image: u("photo-1515886657613-9f3515b0c78f"),
    description: "Lightweight chiffon saree with all-over embroidery. Elegant and easy to drape.",
    sizes: ["Free Size"],
    colors: ["Yellow", "Orange", "Teal"],
    new: false,
    stock: 20
  },
  {
    id: "6",
    name: "Designer Palazzo Suit",
    price: 110.00,
    category: "Suits",
    rating: 4.5,
    reviews: 98,
    image: u("photo-1539109136881-3be0616acf4b"),
    description: "Modern Indo-western palazzo suit with geometric prints. Comfortable for office and casual outings.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White", "Navy"],
    new: false,
    stock: 12
  },
  {
    id: "7",
    name: "Peacock Blue Lehenga",
    price: 389.00,
    category: "Lehengas",
    rating: 4.8,
    reviews: 77,
    image: u("photo-1521672555542-0f97e6408f9e"),
    description: "Exquisite peacock-blue lehenga adorned with hand-embroidered peacock motifs. Makes a bold statement at sangeet and mehndi ceremonies.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Peacock Blue", "Teal"],
    new: true,
    stock: 6
  },
  {
    id: "8",
    name: "Block Print Cotton Kurti",
    price: 54.99,
    category: "Kurtis",
    rating: 4.4,
    reviews: 203,
    image: u("photo-1536246961965-ea5e698bef97"),
    description: "Hand block-printed cotton kurti with Rajasthani motifs. Breathable fabric, perfect for summer and everyday casual wear.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Indigo", "Rust", "Olive"],
    new: false,
    stock: 30
  },
  {
    id: "9",
    name: "Kanjeevaram Silk Saree",
    price: 459.00,
    category: "Sarees",
    rating: 4.9,
    reviews: 188,
    image: u("photo-1523293182086-7651a899d37f"),
    description: "Pure Kanjeevaram silk saree woven with traditional temple borders and rich colour contrasts. A timeless heirloom piece.",
    sizes: ["Free Size"],
    colors: ["Crimson", "Gold", "Emerald"],
    new: false,
    stock: 7
  },
  {
    id: "10",
    name: "Red Net Anarkali",
    price: 229.00,
    category: "Anarkalis",
    rating: 4.7,
    reviews: 112,
    image: u("photo-1519345182560-3f2917c472ef"),
    description: "Flowing red net Anarkali with sequin-embellished yoke and flared skirt. Perfect for festive dinners and receptions.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Wine"],
    new: true,
    stock: 9
  },
  {
    id: "11",
    name: "Chanderi Salwar Suit",
    price: 149.00,
    category: "Suits",
    rating: 4.5,
    reviews: 64,
    image: u("photo-1522337360788-8b13dee7a37e"),
    description: "Elegant Chanderi silk salwar suit with intricate silver zari work. Lightweight and graceful for formal events and pujas.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ivory", "Rose", "Lavender"],
    new: false,
    stock: 14
  },
  {
    id: "12",
    name: "Mirror Work Lehenga",
    price: 599.00,
    category: "Lehengas",
    rating: 5.0,
    reviews: 43,
    image: u("photo-1617711164094-dae2c79b4369"),
    description: "Vibrant mirror-work lehenga from Kutch with hand-stitched shisha embroidery. A showstopper for weddings and cultural festivals.",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Fuchsia", "Orange", "Turquoise"],
    new: true,
    stock: 4
  }
];
